const fakeData = [
    {
        name: "COX'S BAZAR", nickName: 'coxbazar', id: '1', shortDetail: "Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach.", detail: `Cox's Bazar is a city, fishing port, tourism centre and district headquarters in southeastern Bangladesh. It is famous mostly for its long natural sandy beach, and it is infamous for the largest refugee camp in the world. It is located 150 km (93 mi) south of the divisional headquarter city of Chittagong. Cox's Bazar is also known by the name Panowa, which translates literally as "yellow flower". Another old name was "Palongkee".`, imgURL: "https://i.ibb.co/MgH0LxM/cox-bazar.jpg", bgURL: "https://i.ibb.co/k5stTbS/Rectangle-1.jpg", hotelMapImg: "https://i.ibb.co/gtm80Sv/cox-Bazar-Hotel.jpg"
    },
    {
        name: 'SREEMANGAL', nickName: 'sreemangal', id: '2', shortDetail: 'Madhobpur Lake is one of the main tourist attractions in the area,[3][4][5] and is home to the Great White-Bellied Heron, the only confirmed site in Bangladesh.', detail: 'Madhobpur Lake is one of the main tourist attractions in the area,[3][4][5] and is home to the Great White-Bellied Heron, the only confirmed site in Bangladesh.[6] The Baikka beel is also a nearby body of water and home to the Large-billed reed warbler.[7] Sreemangal has been nicknamed the tea capital of Bangladesh, due to the number of tea gardens in the area, and is the place of origin of the Seven Color Tea.', imgURL: "https://i.ibb.co/n0Hh07D/Sreemongol.png", bgURL: "https://i.ibb.co/Dk4HyQ4/sreemangalbg.jpg", hotelMapImg: "https://i.ibb.co/YW2rP4k/sreemangal-Hotel.jpg"
    },
    {
        name: 'SUNDARBANS', nickName: 'sundarbans', id: '3', shortDetail: 'The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal.', detail: "The Sundarbans is a mangrove area in the delta formed by the confluence of the Ganges, Brahmaputra and Meghna Rivers in the Bay of Bengal. It spans from the Hooghly River in India's state of West Bengal to the Baleswar River in Bangladesh. It comprises closed and open mangrove forests, agriculturally used land, mudflats and barren land, and is intersected by multiple tidal streams and channels. ", imgURL: "https://i.ibb.co/XVDbvgG/sundorbon.png", bgURL: 'https://i.ibb.co/9cM6r0P/sundarbans.jpg', hotelMapImg: "https://i.ibb.co/jHRwYNy/sundarban-Hotel.jpg"
    }
]

export default fakeData;